<?
$pageText = !empty($pager) && $pager->total_pages > 1 ? "Page " . $pager->current : "";
$this->placeholder->block('title')->set("Thinking of AlloVince - " . $pageText);
?>
<div class="page-content">
    <?$posts = $pager->items;?>
    <div class="vlist posts">
        <?foreach($posts as $key => $post):?>
        <div class="item <?=$key == 0 ? 'first' : ''?>">
            <div class="item-inline item-title">
                <h3><a href="<?=$this->url->get('/pages/' . $post->slug)?>"><?=$post->title?></a></h3>
                <p class="info">发布时间： <time datetime="<?=$this->tag->isoTime($post->createdAt)?>" data-jstime="<?=$this->tag->jsTime($post->createdAt)?>" class="agotime"><?=$this->tag->datetime($post->createdAt)?></time></p>
            </div>
        </div>
        <?endforeach;?>
    </div>
                    <?$this->partial("partial/paginator", array(
                    'pagerUrl' => '/thinking',
                    'pager' => $pager,
                    ))?>
</div>

